// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuhmbFMoSWC7Qt4VcM9_g7SWRDb7AO2DQ',
    appId: '1:99618230636:web:2cd4870c47c86f40f72349',
    messagingSenderId: '99618230636',
    projectId: 'k-tv-1fdcc',
    authDomain: 'k-tv-1fdcc.firebaseapp.com',
    storageBucket: 'k-tv-1fdcc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs-ZsOOxhowD36T_2AilWJSxbMavEcz5g',
    appId: '1:99618230636:android:be0cccf64c55f67cf72349',
    messagingSenderId: '99618230636',
    projectId: 'k-tv-1fdcc',
    storageBucket: 'k-tv-1fdcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk2JCbk1QbRxeqIjr8wkgd4Y7dhUMw4ZE',
    appId: '1:99618230636:ios:de8ec77571c5d4a2f72349',
    messagingSenderId: '99618230636',
    projectId: 'k-tv-1fdcc',
    storageBucket: 'k-tv-1fdcc.firebasestorage.app',
    iosClientId:
        '99618230636-mirpni93rp5bvlb57n3v3m8jeivhl9mb.apps.googleusercontent.com',
    iosBundleId: 'com.example.kTv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk2JCbk1QbRxeqIjr8wkgd4Y7dhUMw4ZE',
    appId: '1:99618230636:ios:de8ec77571c5d4a2f72349',
    messagingSenderId: '99618230636',
    projectId: 'k-tv-1fdcc',
    storageBucket: 'k-tv-1fdcc.firebasestorage.app',
    iosClientId:
        '99618230636-mirpni93rp5bvlb57n3v3m8jeivhl9mb.apps.googleusercontent.com',
    iosBundleId: 'com.example.kTv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuhmbFMoSWC7Qt4VcM9_g7SWRDb7AO2DQ',
    appId: '1:99618230636:web:557cc50fcd29368cf72349',
    messagingSenderId: '99618230636',
    projectId: 'k-tv-1fdcc',
    authDomain: 'k-tv-1fdcc.firebaseapp.com',
    storageBucket: 'k-tv-1fdcc.firebasestorage.app',
  );
}
