// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuBZKruGPPjeWCN_QUwSZZUKrDr30Xz8k',
    appId: '1:766637910063:web:abe20529369b08c19c3eda',
    messagingSenderId: '766637910063',
    projectId: 'k-tv-e03dc',
    authDomain: 'k-tv-e03dc.firebaseapp.com',
    storageBucket: 'k-tv-e03dc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDESzY1bAUAAveeblUZYkPo92gBLIYSTdc',
    appId: '1:766637910063:android:997170deae4b93ab9c3eda',
    messagingSenderId: '766637910063',
    projectId: 'k-tv-e03dc',
    storageBucket: 'k-tv-e03dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgZm0GqoxXEFTh3pyVKGCz7KLfUbcItVo',
    appId: '1:766637910063:ios:b49101c62d8f7e029c3eda',
    messagingSenderId: '766637910063',
    projectId: 'k-tv-e03dc',
    storageBucket: 'k-tv-e03dc.firebasestorage.app',
    iosClientId: '766637910063-cejevtohejlqq1tugh1p1hg8er73d7i4.apps.googleusercontent.com',
    iosBundleId: 'com.example.kTv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgZm0GqoxXEFTh3pyVKGCz7KLfUbcItVo',
    appId: '1:766637910063:ios:b49101c62d8f7e029c3eda',
    messagingSenderId: '766637910063',
    projectId: 'k-tv-e03dc',
    storageBucket: 'k-tv-e03dc.firebasestorage.app',
    iosClientId: '766637910063-cejevtohejlqq1tugh1p1hg8er73d7i4.apps.googleusercontent.com',
    iosBundleId: 'com.example.kTv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuBZKruGPPjeWCN_QUwSZZUKrDr30Xz8k',
    appId: '1:766637910063:web:51422eb78c1a1b6b9c3eda',
    messagingSenderId: '766637910063',
    projectId: 'k-tv-e03dc',
    authDomain: 'k-tv-e03dc.firebaseapp.com',
    storageBucket: 'k-tv-e03dc.firebasestorage.app',
  );

}